# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 564)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startStopButton2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startStopButton2.sizePolicy().hasHeightForWidth())
        self.startStopButton2.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Pictures/Icons/green-play-button-png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startStopButton2.setIcon(icon)
        self.startStopButton2.setObjectName("startStopButton2")
        self.horizontalLayout.addWidget(self.startStopButton2)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../Pictures/Icons/sa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon1)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scopeButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scopeButton.sizePolicy().hasHeightForWidth())
        self.scopeButton.setSizePolicy(sizePolicy)
        self.scopeButton.setObjectName("scopeButton")
        self.verticalLayout.addWidget(self.scopeButton)
        self.reflectanceButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reflectanceButton.sizePolicy().hasHeightForWidth())
        self.reflectanceButton.setSizePolicy(sizePolicy)
        self.reflectanceButton.setObjectName("reflectanceButton")
        self.verticalLayout.addWidget(self.reflectanceButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scope_dark = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scope_dark.sizePolicy().hasHeightForWidth())
        self.scope_dark.setSizePolicy(sizePolicy)
        self.scope_dark.setObjectName("scope_dark")
        self.verticalLayout_2.addWidget(self.scope_dark)
        self.AbIrradiance = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AbIrradiance.sizePolicy().hasHeightForWidth())
        self.AbIrradiance.setSizePolicy(sizePolicy)
        self.AbIrradiance.setObjectName("AbIrradiance")
        self.verticalLayout_2.addWidget(self.AbIrradiance)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.absorbance = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.absorbance.sizePolicy().hasHeightForWidth())
        self.absorbance.setSizePolicy(sizePolicy)
        self.absorbance.setObjectName("absorbance")
        self.verticalLayout_3.addWidget(self.absorbance)
        self.RelIrradiance = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RelIrradiance.sizePolicy().hasHeightForWidth())
        self.RelIrradiance.setSizePolicy(sizePolicy)
        self.RelIrradiance.setObjectName("RelIrradiance")
        self.verticalLayout_3.addWidget(self.RelIrradiance)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.transmittance = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transmittance.sizePolicy().hasHeightForWidth())
        self.transmittance.setSizePolicy(sizePolicy)
        self.transmittance.setObjectName("transmittance")
        self.verticalLayout_4.addWidget(self.transmittance)
        spacerItem = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.scaleY = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleY.sizePolicy().hasHeightForWidth())
        self.scaleY.setSizePolicy(sizePolicy)
        self.scaleY.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../Pictures/Icons/ScaleY.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scaleY.setIcon(icon2)
        self.scaleY.setObjectName("scaleY")
        self.horizontalLayout_2.addWidget(self.scaleY)
        self.scaleReset = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleReset.sizePolicy().hasHeightForWidth())
        self.scaleReset.setSizePolicy(sizePolicy)
        self.scaleReset.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../Pictures/Icons/Reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scaleReset.setIcon(icon3)
        self.scaleReset.setObjectName("scaleReset")
        self.horizontalLayout_2.addWidget(self.scaleReset)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_6.addWidget(self.graphicsView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 22))
        self.menubar.setObjectName("menubar")
        self.menuSetup = QtWidgets.QMenu(self.menubar)
        self.menuSetup.setObjectName("menuSetup")
        self.menuMesurement = QtWidgets.QMenu(self.menubar)
        self.menuMesurement.setObjectName("menuMesurement")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSetup.menuAction())
        self.menubar.addAction(self.menuMesurement.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startStopButton2.setText(_translate("MainWindow", "Start"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.scopeButton.setText(_translate("MainWindow", "Scope"))
        self.reflectanceButton.setText(_translate("MainWindow", "Reflectance"))
        self.scope_dark.setText(_translate("MainWindow", "Scope-Dark"))
        self.AbIrradiance.setText(_translate("MainWindow", "Abs_Irrandiance"))
        self.absorbance.setText(_translate("MainWindow", "Absorbance"))
        self.RelIrradiance.setText(_translate("MainWindow", "Rel_Irradiance"))
        self.transmittance.setText(_translate("MainWindow", "Transmittance"))
        self.menuSetup.setTitle(_translate("MainWindow", "Setup"))
        self.menuMesurement.setTitle(_translate("MainWindow", "Mesurements"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

